Repository newrelic/node-newrelic, pull requests merged in 2020-12, with the labels that each got.

#558 Release v7.0.2
  NEWS.md
Labels: risk: low, semver: patch

#563 Fixes ENV configuration for Infinite Tracing queue size.
  lib/config/env.js
  test/unit/config/config.test.js
Labels: risk: low, semver: patch

#570 Fix empty log message
  lib/spans/streaming-span-event-aggregator.js
  test/unit/db/query-sample.test.js
Labels: risk: none, semver: patch

#572 Add fastify v3 support
  lib/instrumentation/fastify.js
  test/integration/fastify/naming.tap.js
Labels: risk: medium, semver: minor

#573 Fix Node minimum version message (fixes #557)
  index.js
Labels: risk: none, semver: patch
