Repository newrelic/node-newrelic, pull requests merged in 2020-06, with the labels that each got.

#369 Adds commonly skipped items to npmignore to avoid accidentally publishing
  .npmignore
Labels: risk: low, semver: patch

#365 Add AWS API Gateway V2 Support
  lib/serverless/event-sources.json
Labels: risk: low, semver: minor

#366 Converts transaction 'finalizeName...' unit tests to use tap API.
  test/unit/transaction.test.js
Labels: risk: none, semver: patch

#370 Waits for error to trigger on test before ending transaction.
  test/versioned/redis/redis.tap.js
Labels: risk: none, semver: patch

#371 Moves error data collection checks up to where errors are added
  lib/errors/error-collector.js
  test/integration/distributed-tracing/span-error-attributes.tap.js
  test/unit/errors/error-collector.test.js
Labels: risk: low, semver: patch

#372 Add transaction name to span as intrinsic
  lib/spans/span-context.js
  lib/spans/span-event.js
  lib/spans/streaming-span-event.js
  lib/transaction/index.js
  lib/transaction/trace/segment.js
  lib/transaction/tracer/index.js
  test/integration/distributed-tracing/transaction-span-attributes.tap.js
  test/unit/api/api-custom-attributes.test.js
  test/unit/spans/span-event-aggregator.test.js
  test/unit/spans/span-event.test.js
  test/unit/spans/streaming-span-event.test.js
  test/unit/trace-segment.test.js
  test/unit/transaction.test.js
Labels: risk: low, semver: minor

#374 Add expected error to span
  lib/transaction/index.js
  test/integration/distributed-tracing/span-error-attributes.tap.js
Labels: risk: low, semver: minor

#375 Import NormalizerRule as NormalizerRule instead of Rule
  README.md
  lib/metrics/normalizer.js
Labels: risk: low, semver: patch

#378 Release v6.9.0.
  NEWS.md
Labels: risk: low, semver: minor

#376 Immediately reconnects to infinite tracing endpoint on 200 OK status.
  lib/grpc/connection.js
  lib/spans/streaming-span-event-aggregator.js
  test/integration/grpc/reconnect.tap.js
  test/integration/infinite-tracing-connection.tap.js
  test/unit/grpc/connection.test.js
Labels: risk: low, semver: patch

#377 Adds request headers map key-value paris to Infinite Tracing gRPC metadata
  lib/config/index.js
  lib/grpc/connection.js
  lib/spans/span-streamer.js
  lib/spans/streaming-span-event-aggregator.js
  test/integration/infinite-tracing-connection.tap.js
  test/unit/grpc/connection.test.js
Labels: risk: low, semver: minor

#382 Updates force secret run to only run on branch pushes to main repo.
  .github/workflows/ci-workflow.yml
Labels: risk: none, semver: patch

#381 Adds transaction agent attributes to spans
  lib/header-attributes.js
  lib/instrumentation/core/http.js
  lib/serverless/aws-lambda.js
  lib/shim/message-shim.js
  lib/transaction/index.js
  lib/transaction/trace/index.js
  lib/transaction/trace/segment.js
  test/unit/header-attributes.test.js
  test/unit/instrumentation/http/http.test.js
  test/unit/serverless/aws-lambda.test.js
  test/unit/shim/message-shim.test.js
  test/unit/spans/span-event.test.js
  test/unit/trace.test.js
  test/unit/transaction.test.js
Labels: risk: low, semver: minor

#384 Custom transaction atts to span
  api.js
  lib/prioritized-attributes.js
  lib/spans/span-context.js
  lib/spans/span-event.js
  lib/spans/streaming-span-event.js
  lib/transaction/trace/segment.js
  test/benchmark/attributes/priority-add-max.js
  test/integration/api/custom-attribute-span-propogation.tap.js
  test/unit/attributes.test.js
  test/unit/high-security.test.js
  test/unit/prioritized-attributes.test.js
  test/unit/spans/span-event.test.js
  test/unit/spans/streaming-span-event.test.js
Labels: risk: low, semver: minor

#387 Further redis test flicker reduction
  test/versioned/redis/redis.tap.js
Labels: risk: none, semver: patch

#389 Converted trace-segment tests to tap
  test/unit/trace-segment.test.js
Labels: ready for review, risk: low, semver: minor

#386 Parent span event attrs
  lib/transaction/trace/index.js
  test/unit/trace.test.js
Labels: ready for review, risk: low, semver: minor

#388 Segment attributes intended for Spans should be explicitly added to Spans
  lib/instrumentation/core/http-outbound.js
  lib/transaction/index.js
  test/unit/error_events.test.js
  test/unit/instrumentation/http/outbound.test.js
Labels: risk: low, semver: minor

#392 Release v6.10.0
  NEWS.md
  THIRD_PARTY_NOTICES.md
Labels: risk: low, semver: minor

#393 Update newrelic.js
  newrelic.js
Labels: risk: low, semver: patch

#395 Tap test conversions
  test/unit/collector/key-parser.test.js
  test/unit/hashes.test.js
  test/unit/instrumentation/core/inspector.test.js
  test/unit/metric/normalizer-tx-segment.test.js
  test/unit/protocols.test.js
  test/unit/util/hashes.test.js
  test/unit/util/label-parser.test.js
  test/unit/util/obfuscate-sql.test.js
Labels: ready for review, risk: low, semver: minor

#408 Update LICENSE to Apache License and move Symantec cert license
  LICENSE
  THIRD_PARTY_NOTICES.md
  package.json
Labels: risk: low, semver: minor

#410 Adding CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: risk: none, semver: minor

#412 Updates readme to appropriately mention Apache 2.0.
  README.md
Labels: risk: low, semver: patch

#409 Removes unused code injector functionality.
  lib/config/default.js
  lib/config/env.js
  lib/config/index.js
  lib/injector.js
  lib/shimmer.js
  package-lock.json
  package.json
  test/unit/config/config.test.js
  test/unit/licenses.json
Labels: risk: low, semver: patch

#354 Fastify Route Naming
  lib/feature_flags.js
  lib/instrumentation/fastify.js
  lib/instrumentation/fastify/spec-builders.js
  lib/instrumentations.js
  lib/shim/webframework-shim.js
  package-lock.json
  package.json
  test/integration/fastify/errors.tap.js
  test/integration/fastify/naming.tap.js
  test/unit/feature_flag.test.js
  test/versioned/fastify/integration.tap.js
  test/versioned/fastify/newrelic.js
  test/versioned/fastify/package.json
Labels: risk: low, semver: minor
