Repository newrelic/node-newrelic, pull requests merged in 2020-07, with the labels that each got.

#415 Updated contributing guide
  CONTRIBUTING.md
Labels: ready for review, risk: low, semver: patch

#416 Update third party notices
  THIRD_PARTY_NOTICES.md
  THIRD_PARTY_NOTICES_ADDENDUM.md
  third_party_manifest.json
Labels: risk: low, semver: patch

#417 Cleanup
  lib/stats/index.js
  test/integration/distributed-tracing/trace-context-cross-agent.tap.js
  test/lib/fake-collector.js
  test/unit/instrumentation/http/outbound.test.js
Labels: ready for review, risk: none, semver: patch

#421 PR version verbage
  CONTRIBUTING.md
Labels: ready for review, risk: low, semver: minor

#422 Adds some additional guidance to bug issue template.
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: risk: low, semver: patch

#425 Updates news wording.
  NEWS.md
Labels: risk: none

#426 Fixes test-utilities and jsv third party notices.
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: risk: low, semver: patch

#430 Bump @newrelic/koa version
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  test/unit/licenses.json
  third_party_manifest.json
Labels: risk: low, semver: minor

#429 Updates CI badges to link to each workflow page.
  README.md
Labels: risk: low, semver: patch

#431 Removing Old Security Language
  SECURITY.md
Labels: risk: low, semver: patch

#432 Manually matched license to file for through dependency for third par…
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: risk: low, semver: patch

#433 Adds additional dependency language to bottom of third party notices.
  THIRD_PARTY_NOTICES.md
  THIRD_PARTY_NOTICES_ADDENDUM.md
Labels: risk: low, semver: patch

#434 Bumps @newrelic/superagent to ^3.0.0.
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  test/unit/licenses.json
  third_party_manifest.json
Labels: risk: low, semver: minor

#437 Update Readme, templates and contributing doc
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/troubleshooting.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  ROADMAP_Node.md
Labels: ready for review, risk: none, semver: patch

#440 Bumps node-test-utilities to ^4.0.0.
  package-lock.json
  package.json
Labels: risk: low, semver: patch

#442 Issue #343: Upgrade async to 3.2.0
  lib/environment.js
  package-lock.json
  package.json
  test/integration/instrumentation/oracle.tap.js
Labels: risk: low, semver: patch

#443 Updates third party notices to capture node-test-utilities and async version bumps
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: risk: low, semver: patch

#447 Removes the 'remove this...' language from readme.
  README.md
Labels: risk: low, semver: patch

#448 Fixes first-line formatting for license file.
  LICENSE
Labels: risk: none, semver: patch
