Repository newrelic/node-newrelic, pull requests merged in 2020-11, with the labels that each got.

#524 Check that Node version is >=10 and <15
  index.js
Labels: ready for review, risk: low, semver: patch

#527 Remove setIgnoreTransaction API method
  api.js
  test/unit/api/api-set-ignore-transaction.test.js
  test/unit/api/stub.test.js
  test/unit/rum.test.js
  test/unit/transaction.test.js
  test/versioned/express/ignoring.tap.js
  test/versioned/hapi/hapi-17/ignoring.tap.js
  test/versioned/hapi/hapi-post-18/ignoring.tap.js
  test/versioned/hapi/hapi-pre-17/ignoring.tap.js
  test/versioned/restify/restify-post-7/ignoring.tap.js
  test/versioned/restify/restify-pre-7/ignoring.tap.js
Labels: risk: low, semver: major

#528 Remove deprecated http response attributes
  lib/instrumentation/core/http.js
  lib/serverless/aws-lambda.js
  test/integration/transaction/errors.tap.js
  test/lib/fixtures.js
  test/unit/serverless/aws-lambda.test.js
Labels: ready for review, risk: low, semver: major

#529 Remove node <=9.x.x version checks on http instrumentation
  lib/instrumentation/core/http.js
Labels: ready for review, risk: low, semver: major

#531 Remove node v10 check from http outbound test.
  test/unit/instrumentation/http/outbound.test.js
Labels: ready for review, risk: low, semver: major

#532 Remove Node v7 checks from tests
  test/integration/instrumentation/http.tap.js
  test/unit/logger.test.js
Labels: ready for review, risk: low, semver: major

#533 Remove api.custom_parameters_enabled config item
  lib/config/default.js
  lib/config/env.js
  lib/config/index.js
Labels: ready for review, risk: medium, semver: major

#535 Removed deprecation warnings invalid config items
  lib/config/index.js
Labels: ready for review, risk: low, semver: major

#538 Update New Relic dependencies
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  third_party_manifest.json
Labels: ready for review, risk: low, semver: major

#539 Remove koa skip from version test runs
  bin/run-versioned-tests.sh
Labels: ready for review, risk: low, semver: patch

#537 Remove dt methods
  examples/api/distributed-tracing/example1-background.js
  lib/transaction/dt-payload.js
  lib/transaction/handle.js
  lib/transaction/index.js
  test/unit/analytics_events.test.js
  test/unit/api/api-transaction-handle.test.js
  test/unit/db/trace.test.js
  test/unit/distributed_tracing/dt-cats.test.js
  test/unit/error_events.test.js
  test/unit/errors/error-collector.test.js
  test/unit/metrics-recorder/distributed-trace.test.js
  test/unit/metrics-recorder/http.test.js
  test/unit/trace.test.js
  test/unit/transaction.test.js
Labels: risk: medium, semver: major

#540 Skip LASP integration tests for now (issue with service)
  test/integration/agent/lasp-send-trace.tap.js
  test/integration/lasp_connect.tap.js
Labels: risk: medium, semver: patch

#541 Release v7.0.0
  NEWS.md
  third_party_manifest.json
Labels: risk: medium, semver: major

#545 Format spans drained from queue
  lib/spans/span-streamer.js
  test/unit/spans/span-streamer.test.js
Labels: ready for review, risk: low, semver: patch

#548 update tap
  package-lock.json
  package.json
Labels: ready for review, risk: low, semver: patch

#550 Update grpc-js version to v1.2.0
  package-lock.json
  package.json
Labels: ready for review, risk: low, semver: patch

#551 Update third-party manifest and notices
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: risk: none, semver: patch

#552 Release v7.0.1
  NEWS.md
Labels: risk: low, semver: patch

#556 Capture http.statusCode on web response of async invoked lambda
  lib/serverless/aws-lambda.js
  test/unit/serverless/aws-lambda.test.js
Labels: risk: low, semver: patch
