Repository newrelic/node-newrelic, pull requests merged in 2020-05, with the labels that each got.

#347 Update GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: risk: none

#350 Adds trimming of license key string to help avoid copy-paste issues.
  lib/config/index.js
  test/unit/config/config.test.js
Labels: risk: medium, semver: patch

#348 Bumps @newrelic/native-metrics to ^5.1.0.
  package-lock.json
  package.json
Labels: risk: low, semver: minor

#355 Test filtering
  .github/workflows/ci-workflow.yml
  bin/run-versioned-tests.sh
  bin/ssl.sh
  package-lock.json
  package.json
  test/integration/agent/agent-restart-listener.tap.js
  test/integration/agent/serverless-harvest.tap.js
  test/integration/agent/start-stop.tap.js
  test/integration/api/connection.tap.js
  test/integration/api/error-data.tap.js
  test/integration/api/metric-data.tap.js
  test/integration/api/transaction-sample-data.tap.js
  test/integration/index/index-bad-config.tap.js
  test/integration/index/index-bad-version.tap.js
  test/integration/index/index.tap.js
  test/integration/lasp_connect.tap.js
  test/integration/proxy-api-connection-auth.tap.js
  test/integration/proxy-api-connection-noproxy.tap.js
  test/integration/proxy-api-connection-port.tap.js
  test/integration/proxy-api-connection-ssl.tap.js
  test/smoke/newrelic.js
Labels: ready for review, risk: low, semver: minor

#351 Converts most of the collector API unit tests to use the tap API.
  test/unit/collector/api-connect.test.js
  test/unit/collector/api-login.test.js
  test/unit/collector/api-run-lifecycle.test.js
  test/unit/collector/api.test.js
Labels: risk: none, semver: patch

#356 Converts parse-response unit tests to tap API.
  test/unit/collector/parse-response.test.js
Labels: risk: none, semver: patch

#358 Check for license before running test
  test/integration/agent/lasp-send-trace.tap.js
Labels: ready for review, risk: none

#359 Updates release notes for 6.8.0.
  NEWS.md
Labels: risk: medium, semver: minor

#360 Don't skip tests if secrets should be available
  .github/workflows/ci-workflow.yml
  test/helpers/secrets.js
  test/integration/agent/agent-restart-listener.tap.js
  test/integration/agent/lasp-send-trace.tap.js
  test/integration/agent/serverless-harvest.tap.js
  test/integration/agent/start-stop.tap.js
  test/integration/api/connection.tap.js
  test/integration/api/error-data.tap.js
  test/integration/api/metric-data.tap.js
  test/integration/api/transaction-sample-data.tap.js
  test/integration/index/index-bad-config.tap.js
  test/integration/index/index-bad-version.tap.js
  test/integration/index/index.tap.js
  test/integration/lasp_connect.tap.js
  test/integration/proxy-api-connection-noproxy.tap.js
  test/integration/proxy-api-connection-port.tap.js
  test/integration/proxy-api-connection-ssl.tap.js
Labels: ready for review, risk: none, semver: patch
