Repository newrelic/node-newrelic, pull requests merged in 2020-09, with the labels that each got.

#469 ci: Add Open Source Policy Workflow
  .github/workflows/repolinter.yml
Labels: risk: none, semver: patch

#472 Update readme with community-plus header
  README.md
Labels: risk: none, semver: patch

#479 fix: Check for named pipe before each payload write
  lib/collector/serverless.js
Labels: risk: low, semver: patch

#480 Removes repo's code of conduct as there's now a centralized one.
  CODE_OF_CONDUCT.md
Labels: risk: none, semver: patch

#481 Updates CoC link in contrib to central location.
  CONTRIBUTING.md
Labels: risk: none, semver: patch

#482 Release 6.13.1
  NEWS.md
Labels: risk: low, semver: patch

#486 Shim documentation update
  examples/shim/Webframework-Simple.md
Labels: ready for review, risk: none, semver: patch
