Repository newrelic/node-newrelic, pull requests merged in 2020-08, with the labels that each got.

#450 On failed instrumentation, prevent multiple requires from re-wrapping shims
  lib/shimmer.js
  test/integration/shimmer/module-load-fixture-errored.js
  test/integration/shimmer/module-load-fixture.js
  test/integration/shimmer/module-load.test.js
  test/unit/shimmer.test.js
Labels: feature-request, risk: low, semver: patch

#454 Bumps @newrelic/aws-sdk to ^2.0.0.
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  test/unit/licenses.json
  third_party_manifest.json
Labels: risk: low, semver: minor

#458 Bumps @newrelic/native-metrics to ^5.3.0.
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  test/unit/licenses.json
Labels: risk: low, semver: minor

#456 Fix large JSON inserts obfuscation
  lib/util/sql/obfuscate.js
  test/unit/util/obfuscate-sql.test.js
Labels: risk: low, semver: patch

#461 Release/v6.12.0
  NEWS.md
Labels: ready for review, risk: low, semver: minor

#465 Fixes transaction trace request uri handling.
  lib/attributes.js
  lib/prioritized-attributes.js
  lib/transaction/trace/index.js
  test/unit/attributes.test.js
  test/unit/prioritized-attributes.test.js
  test/unit/trace.test.js
Labels: risk: low, semver: patch

#466 Release v6.12.1
  NEWS.md
Labels: risk: low, semver: patch

#468 Release 6.13.0.
  NEWS.md
Labels: risk: medium, semver: minor
