Repository newrelic/node-newrelic, pull requests merged in 2020-10, with the labels that each got.

#490 Remove lodash
  package-lock.json
  package.json
  test/integration/config/attribute-cat.tap.js
  test/unit/high-security.test.js
Labels: ready for review, risk: low, semver: patch

#491 Remove lodash from third party files
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: ready for review, risk: none, semver: patch

#492 Updates release notes for 6.13.2 release.
  NEWS.md
Labels: ready for review

#495 Fix gRPC disconnect error
  lib/grpc/connection.js
  package-lock.json
  package.json
Labels: risk: low, semver: patch

#499 Infinite tracing logging modifications
  lib/grpc/connection.js
  lib/spans/span-streamer.js
Labels: risk: low, semver: patch

#501 Standardize headers in NEWS.md
  NEWS.md
Labels: ready for review, risk: none, semver: patch

#503 Fix ignored status codes
  lib/errors/error-collector.js
  lib/errors/index.js
  lib/spans/span-context.js
  lib/spans/span-event.js
  lib/spans/streaming-span-event.js
  lib/transaction/index.js
  test/integration/distributed-tracing/span-error-attributes.tap.js
  test/unit/error_events.test.js
  test/unit/errors/ignore.test.js
Labels: risk: low, semver: patch

#504 Adds additional metrics/logging to better enable infinite tracing troubleshooting
  lib/agent.js
  lib/metrics/names.js
  lib/spans/span-streamer.js
  lib/spans/streaming-span-event-aggregator.js
Labels: risk: low, semver: patch

#520 Release v6.14.0
  NEWS.md
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: risk: low, semver: minor

#522 Adds additional logging to W3C tracecontext header creation.
  lib/transaction/tracecontext.js
Labels: risk: low, semver: patch

#519 Remove Node v8 from CI
  .github/workflows/ci-workflow.yml
  package.json
  test/versioned/amqplib/package.json
  test/versioned/bluebird/package.json
  test/versioned/cassandra-driver/package.json
  test/versioned/cls/package.json
  test/versioned/connect/package.json
  test/versioned/director/package.json
  test/versioned/express/package.json
  test/versioned/fastify/package.json
  test/versioned/generic-pool/package.json
  test/versioned/hapi/hapi-17/package.json
  test/versioned/hapi/hapi-post-18/package.json
  test/versioned/hapi/hapi-pre-17/package.json
  test/versioned/ioredis/package.json
  test/versioned/mongodb/package.json
  test/versioned/mysql/package.json
  test/versioned/mysql2/package.json
  test/versioned/pg/pg-post-7/package.json
  test/versioned/pg/pg-pre-7/package.json
  test/versioned/redis/package.json
  test/versioned/restify/restify-pre-7/package.json
Labels: risk: low, semver: major
