Repository newrelic/node-newrelic, pull requests merged in 2021-12, with the labels that each got.

#989 Adds metrics for tracking when instrumentation is applied
  lib/metrics/names.js
  lib/shimmer.js
  test/integration/module-loading/module-loading.tap.js
  test/integration/module-loading/node_modules/customTestPackage/package.json
  test/versioned/express/ignoring.tap.js
  test/versioned/hapi/hapi-17/ignoring.tap.js
  test/versioned/hapi/hapi-post-18/ignoring.tap.js
  test/versioned/hapi/hapi-pre-17/ignoring.tap.js
  test/versioned/restify/restify-post-7/ignoring.tap.js
  test/versioned/restify/restify-pre-7/ignoring.tap.js
Labels: risk: low, semver: minor

#1002 Fixes an issue where multiple calls to instrumentLoadedModule resulted in reinstrumenting
  api.js
  lib/shimmer.js
  test/integration/api/instrument-loaded.tap.js
  test/unit/api/api-instrument-loaded-module.test.js
Labels: semver: patch

#997 Updates to run external module versioned tests cloned from repos
  .gitignore
  bin/git-commands.js
  bin/run-versioned-tests.sh
  package-lock.json
  package.json
  test/versioned-external/checkout-external-tests.js
  test/versioned-external/external-repos.js
  test/versioned-external/readme.md
  third_party_manifest.json
Labels: risk: low, semver: patch

#1001 fix canonicalization if-condition
  lib/config/index.js
Labels: semver: patch
