Repository newrelic/node-newrelic, pull requests merged in 2021-03, with the labels that each got.

#643 setImmediate no longer binds/propagates segments for an ended transaction
  lib/instrumentation/core/timers.js
  test/integration/core/timers.tap.js
Labels: risk: low, semver: patch

#645 Defaults the application name when running in serverless mode.
  lib/config/index.js
  test/unit/config/config.test.js
Labels: risk: low, semver: patch

#639 [Snyk] Upgrade @grpc/grpc-js from 1.2.5 to 1.2.6
  package-lock.json
  package.json
Labels: risk: low, semver: patch

#646 Adds support metric for cert usage.
  lib/agent.js
  lib/metrics/names.js
Labels: risk: low, semver: patch

#648 Index bad config
  test/integration/agent/serverless-harvest.tap.js
  test/integration/index/index-bad-config.tap.js
Labels: risk: low, semver: patch

#650 Adds auto creation of PR to release note generation script
  bin/generate-release-notes.js
  bin/git-commands.js
  bin/github.js
Labels: risk: none

#651 Adds a GitHub action for generating the release notes PR.
  .github/workflows/create-release-notes-pr.yml
  bin/generate-release-notes.js
Labels: risk: none

#662 Fixes bug where truncated segments/spans would not have appropriate category
  lib/spans/span-event.js
  lib/spans/streaming-span-event.js
  test/unit/spans/span-event.test.js
  test/unit/spans/streaming-span-event.test.js
Labels: risk: low, semver: patch

#668 Add certificate_bundle feature flag to enable deprecation and removal efforts
  lib/collector/http-agents.js
  lib/collector/remote-method.js
  lib/feature_flags.js
  test/integration/collector-remote-method.tap.js
  test/integration/keep-alive.tap.js
  test/unit/feature_flag.test.js
Labels: risk: low, semver: minor

#678 Migrates from .npmignore to using 'files' list in package.json.
  .npmignore
  package.json
Labels: risk: medium, semver: patch

#700 Adds module root to shim.require() logging to make issues more clear.
  lib/shim/shim.js
Labels: risk: low, semver: patch

#679 The NEW_RELIC_NO_CONFIG_FILE env var is now not needed to run the agent without config file
  lib/config/index.js
  test/integration/logger.tap.js
  test/unit/config/config.test.js
Labels: risk: medium, semver: minor

#703 Update warning log message when cannot find config or bad config file
  bin/test-naming-rules.js
  lib/config/index.js
Labels: risk: none, semver: patch

#706 Distributed tracing is set to enabled in newrelic.js template configuration file
  newrelic.js
  test/lib/metrics_helper.js
  test/unit/api/api-get-linking-metadata.test.js
  test/unit/metrics-recorder/http.test.js
  test/unit/metrics-recorder/queue-time-http.test.js
  test/unit/shim/transaction-shim.test.js
Labels: risk: none, semver: patch

#712 Clears error collections on transaction end after processing.
  lib/instrumentation/core/http.js
  lib/transaction/index.js
  test/unit/transaction.test.js
Labels: risk: medium, semver: patch

#718 Adds active transaction check for parentSegment to promise tracking
  lib/instrumentation/core/async_hooks.js
  test/integration/core/async_hooks.js
Labels: risk: medium, semver: patch

#720 Bump grpc js dependencies
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  third_party_manifest.json
Labels: risk: low, semver: patch

#721 Bumps dev sup-dep to get rid of npm audit warning.
  package-lock.json
Labels: risk: none, semver: patch

#726 Fixes infinite tracing reconnect memory leak
  lib/grpc/connection.js
  lib/spans/create-span-event-aggregator.js
  test/integration/grpc/reconnect.tap.js
  test/integration/infinite-tracing-connection.tap.js
  test/unit/grpc/connection.test.js
  test/unit/spans/create-span-event-aggregator.test.js
  test/unit/trace.test.js
Labels: risk: low, semver: patch
