Repository newrelic/node-newrelic, pull requests merged in 2021-07, with the labels that each got.

#792 added option to bind promises for cursor methods in mongodb
  lib/instrumentation/mongodb.js
  test/versioned/mongodb/cursor-duration.tap.js
  test/versioned/mongodb/package.json
Labels: risk: low, semver: patch

#778 Upgrade https-proxy-agent to v5.0.0
  package-lock.json
  package.json
Labels: risk: medium, semver: patch

#805 Pin mongodb versioned tests <4
  test/versioned/mongodb/package.json
Labels: risk: low, semver: patch

#808 flipped certifcate_bundle flag to default to false
  lib/feature_flags.js
Labels: semver: major

#809 removed serverless_mode as a configurable feature flag and moved into…
  lib/config/index.js
  lib/feature_flags.js
  test/unit/config/config.test.js
Labels: semver: major

#812 Remove Node v10 from ci version matrix.
  .github/workflows/ci-workflow.yml
  .github/workflows/smoke-test-workflow.yml
Labels: risk: low, semver: patch

#813 Linting always uses latest LTS. Bumped to setup-node@v2.
  .github/workflows/ci-workflow.yml
  .github/workflows/smoke-test-workflow.yml
Labels: risk: low

#815 Update Nodejs engines field to >=12
  index.js
  package.json
Labels: risk: low, semver: major

#819 Add hapi 19 20
  test/versioned/hapi/hapi-post-18/errors.tap.js
  test/versioned/hapi/hapi-post-18/package.json
Labels: risk: low, semver: minor

#820 Removes comments around replacing uncaught tap override
  test/integration/instrumentation/http.tap.js
  test/integration/instrumentation/q.tap.js
  test/integration/instrumentation/when.tap.js
  test/integration/transaction/tracer.tap.js
  test/lib/agent_helper.js
  test/unit/errors/error-collector.test.js
  test/unit/instrumentation/core/domain.test.js
  test/unit/instrumentation/core/globals.test.js
  test/unit/instrumentation/http/http.test.js
  test/unit/serverless/aws-lambda.test.js
Labels: risk: low, semver: patch
