Repository newrelic/node-newrelic, pull requests merged in 2021-08, with the labels that each got.

#827 mongo v4 fixes
  .eslintrc.js
  lib/instrumentation/mongodb.js
  lib/instrumentation/mongodb/common.js
  lib/instrumentation/mongodb/constants.js
  lib/instrumentation/mongodb/v2-mongo.js
  lib/instrumentation/mongodb/v3-mongo.js
  lib/instrumentation/mongodb/v4-mongo.js
  package-lock.json
  test/.eslintrc
  test/versioned/mongodb/collection-common.js
  test/versioned/mongodb/collection-find.tap.js
  test/versioned/mongodb/collection-index.tap.js
  test/versioned/mongodb/collection-misc.tap.js
  test/versioned/mongodb/collection-update.tap.js
  test/versioned/mongodb/cursor.tap.js
  test/versioned/mongodb/db.tap.js
  test/versioned/mongodb/package.json
Labels: risk: low, semver: minor

#828 Set agent to 'started' upon completing reconnect to New Relic servers
  lib/agent.js
  lib/collector/api.js
  test/integration/api/shutdown.tap.js
  test/integration/newrelic-response-handling.tap.js
  test/unit/agent/agent.test.js
Labels: risk: medium, semver: patch

#830 Fix postgres pg module Promise based query timings
  lib/instrumentation/pg.js
  test/unit/instrumentation/postgresql.test.js
  test/versioned/pg/pg-post-7/pg.common.js
Labels: risk: medium, semver: patch

#843 ported remaining instrumentation unit tests to use tap exclusively
  test/unit/instrumentation/connect.test.js
  test/unit/instrumentation/generic-pool.test.js
  test/unit/instrumentation/hapi.test.js
  test/unit/instrumentation/memcached.test.js
  test/unit/instrumentation/postgresql.test.js
  test/unit/instrumentation/redis-connection.js
  test/unit/instrumentation/redis.test.js
Labels: risk: low

#847 fixed connect to properly set transaction name with url of route
  lib/instrumentation/connect.js
  test/versioned/connect/error-intercept.tap.js
  test/versioned/connect/package.json
  test/versioned/connect/route.tap.js
Labels: risk: low, semver: minor

#849 added new feature flag to remove the promise destroy hook
  lib/feature_flags.js
  lib/instrumentation/core/async_hooks.js
  test/integration/core/async_hooks-new-promise-unresolved.tap.js
  test/integration/core/async_hooks-new-promise.js
  test/unit/feature_flag.test.js
Labels: risk: low, semver: minor

#859 Connect harvest limit
  lib/config/index.js
  lib/spans/span-event-aggregator.js
  test/unit/config/config-server-side.test.js
  test/unit/spans/span-event-aggregator.test.js
Labels: risk: low, semver: patch
