Repository newrelic/node-newrelic, pull requests merged in 2021-11, with the labels that each got.

#968 Adds graceful handling of null input to cpu and memory parse proc methods
  lib/parse-proc-cpuinfo.js
  lib/parse-proc-meminfo.js
  test/unit/parse-proc-cpuinfo.test.js
  test/unit/parse-proc-meminfo.test.js
Labels: risk: low, semver: patch

#971 added logic to add error when unhandledRejection occurs during lambda handler
  lib/serverless/aws-lambda.js
  test/unit/serverless/aws-lambda.test.js
Labels: semver: patch

#975 Introduces a context tracking API.
  lib/agent.js
  lib/context-manager/create-context-manager.js
  lib/context-manager/diagnostics/legacy-diagnostic-context-manager.js
  lib/context-manager/legacy-context-manager.js
  lib/instrumentation/promise.js
  lib/shim/shim.js
  lib/shim/transaction-shim.js
  lib/transaction/tracer/index.js
  package.json
  test/unit/context-manager/create-context-manager.test.js
  test/unit/context-manager/legacy-context-manager.test.js
  test/unit/context-manager/legacy-context-tests.js
  test/unit/context-manager/legacy-diagnostic-context-manager.test.js
  third_party_manifest.json
Labels: risk: high, semver: patch

#979 added code to properly bind promises in recordConsume
  lib/shim/message-shim.js
  test/unit/shim/message-shim.test.js
Labels: semver: patch

#980 Adds a hook prior to module load for doing early-instrumentation
  api.js
  lib/shimmer.js
  test/integration/module-loading/module-loading.tap.js
  test/lib/agent_helper.js
  test/unit/shimmer.test.js
Labels: risk: high, semver: minor

#986 Updates module onResolved hooks to only fire the first time we've see…
  lib/shimmer.js
  test/helpers/require-module-1.js
  test/helpers/require-module-2.js
  test/unit/shimmer.test.js
Labels: semver: patch

#985 Removes tracer.segment
  lib/transaction/tracer/index.js
  test/benchmark/shim/record.bench.js
  test/benchmark/tracer/bindFunction.bench.js
  test/benchmark/tracer/segments.bench.js
  test/benchmark/tracer/transaction.bench.js
  test/benchmark/tracer/utilities.bench.js
  test/benchmark/webframework-shim/recordMiddleware.bench.js
  test/integration/core/async_hooks-new-promise.js
  test/integration/core/async_hooks.js
  test/integration/core/net.tap.js
  test/integration/core/timers.tap.js
  test/integration/instrumentation/promises/methods.js
  test/integration/transaction/tracer.tap.js
  test/lib/agent_helper.js
  test/unit/api/api-start-background-transaction.test.js
  test/unit/api/api-start-web-transaction.test.js
  test/unit/instrumentation/core/promises.test.js
  test/unit/instrumentation/http/outbound.test.js
  test/unit/shim/shim.test.js
  test/unit/transaction.test.js
Labels: risk: low, semver: patch

#987 Moves methods.js under bluebird versioned test folder.
  test/versioned/bluebird/methods.js
  test/versioned/bluebird/methods.tap.js
Labels: risk: low, semver: patch

#994 Limits redis version.
  test/versioned/redis/package.json
Labels: risk: low, semver: patch
