Repository newrelic/node-newrelic, pull requests merged in 2021-09, with the labels that each got.

#863 Add span event max samples config
  lib/collector/facts.js
  lib/config/default.js
  lib/config/env.js
  lib/config/index.js
  lib/spans/span-event-aggregator.js
  test/unit/config/config-defaults.test.js
  test/unit/config/config-env.test.js
  test/unit/facts.test.js
  test/unit/spans/span-event-aggregator.test.js
Labels: risk: low, semver: minor

#861 add support for mongo connection strings that are to a cluster, added…
  lib/instrumentation/mongodb/common.js
  lib/instrumentation/mongodb/v3-mongo.js
  lib/instrumentation/mongodb/v4-mongo.js
  package-lock.json
  test/versioned/mongodb/collection-common.js
  test/versioned/mongodb/collection-index.tap.js
  test/versioned/mongodb/common.js
Labels: risk: medium, semver: patch

#879 Update default span event limit to 2000
  lib/spans/span-event-aggregator.js
  test/unit/spans/span-event-aggregator.test.js
Labels: risk: low, semver: patch

#881 fixed tests that broke when running on Node.js v16.9.0
  test/integration/instrumentation/http.tap.js
  test/versioned/express/render.tap.js
Labels: risk: low

#885 Adds max samples env vars
  lib/config/default.js
  lib/config/env.js
  test/unit/config/config-env.test.js
Labels: risk: low, semver: patch

#887 Enable dt by default
  lib/config/default.js
  test/integration/cat/background.tap.js
  test/integration/cat/cat.tap.js
  test/integration/cat/cross_process.tap.js
  test/integration/cat/server2.js
  test/unit/agent/intrinsics.test.js
  test/unit/db/query-trace-aggregator.test.js
  test/unit/errors/error-collector.test.js
  test/unit/instrumentation/http/http.test.js
  test/unit/instrumentation/http/outbound.test.js
  test/unit/shim/message-shim.test.js
  test/unit/transaction.test.js
  test/versioned/amqplib/callback.tap.js
  test/versioned/amqplib/promises.tap.js
  test/versioned/express/segments.tap.js
  test/versioned/hapi/hapi-17/segments.tap.js
  test/versioned/hapi/hapi-post-18/segments.tap.js
  test/versioned/hapi/hapi-pre-17/segments-v16.tap.js
Labels: risk: low, semver: minor

#897 Update harvest interval in comments
  lib/config/default.js
Labels: risk: none, semver: patch

#899 Deprecates Cross Application Tracing (CAT).
  lib/config/default.js
  lib/config/index.js
  test/unit/config/config-defaults.test.js
  test/unit/config/config-server-side.test.js
  test/unit/errors/error-collector.test.js
  test/unit/instrumentation/http/http.test.js
  test/unit/instrumentation/http/outbound.test.js
  test/unit/instrumentation/http/synthetics.test.js
  test/unit/shim/message-shim.test.js
  test/unit/shim/transaction-shim.test.js
  test/unit/transaction.test.js
  test/versioned/amqplib/callback.tap.js
  test/versioned/amqplib/promises.tap.js
Labels: risk: low, semver: patch

#902 Fixes transaction-shim.handleCATHeaders() handling of DT headers
  lib/shim/transaction-shim.js
  test/unit/shim/transaction-shim.test.js
  test/versioned/amqplib/callback.tap.js
  test/versioned/amqplib/promises.tap.js
Labels: risk: low, semver: patch

#910 support cassandra-driver >4
  lib/instrumentation/cassandra-driver.js
  package-lock.json
  test/versioned/cassandra-driver/package.json
  test/versioned/cassandra-driver/query.tap.js
Labels: risk: low, semver: minor

#932 Fix opaque timer issue
  lib/instrumentation/core/timers.js
  test/integration/core/timers.tap.js
  test/lib/agent_helper.js
  test/versioned/mongodb/collection-common.js
  test/versioned/mongodb/cursor.tap.js
Labels: risk: low, semver: patch
