Repository newrelic/node-newrelic, pull requests merged in 2021-02, with the labels that each got.

#606 bump grpc-js version to v1.2.5
  package-lock.json
  package.json
Labels: ready for review, risk: low, semver: patch

#607 Update release notes
  NEWS.md
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: ready for review, risk: low

#619 Adds create-release workflow and supporting scripts
  .github/workflows/create-release.yml
  bin/check-workflow-run.js
  bin/create-release.js
  bin/generate-release-notes.js
  bin/github.js
  bin/update-changelog-version.js
  package-lock.json
  package.json
Labels: risk: low, semver: patch

#623 Adds handling of unformatted PR descriptions for release notes.
  bin/generate-release-notes.js
Labels: risk: low

#622 Stops calling send() on streaming span aggregator on initial harvest.
  lib/agent.js
  lib/spans/streaming-span-event-aggregator.js
Labels: risk: low, semver: patch

#621 Fixes infinite tracing reconnect handling
  lib/grpc/connection.js
  test/integration/grpc/reconnect.tap.js
Labels: risk: low, semver: patch

#628 Prepare release
  NEWS.md
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: risk: low, semver: patch

#630 Fix create-release action to use branch reference
  .github/workflows/create-release.yml
  bin/check-workflow-run.js
  bin/create-release.js
Labels: risk: low, semver: patch

#633 Removes create-release GitHub action.
  .github/workflows/create-release.yml
Labels: risk: none

#635 CI cleanup
  bin/run-versioned-tests.sh
  bin/travis-install-gcc5.sh
  bin/travis-install-mongo.sh
  bin/travis-node.sh
  bin/travis-setup.sh
Labels: risk: low

#636 Improves clarity of what went wrong with no log file or disabled agent.
  index.js
  lib/config/index.js
Labels: risk: low, semver: patch

#638 Do not throw error when headers is string passed into acceptDistributedTraceHeaders
  lib/transaction/index.js
  test/lib/cross_agent_tests/distributed_tracing/distributed_tracing.json
  test/unit/transaction.test.js
Labels: risk: low, semver: patch

#640 Do not redirect preconnect
  lib/collector/api.js
  lib/collector/remote-method.js
  test/integration/collector-remote-method.tap.js
  test/integration/keep-alive.tap.js
  test/unit/collector/api-connect.test.js
  test/unit/collector/remote-method.test.js
Labels: risk: medium, semver: patch
