Repository newrelic/node-newrelic, pull requests merged in 2021-01, with the labels that each got.

#574 Use 15 char hex to guarantee signed long fit
  lib/db/slow-query.js
  test/unit/db/query-trace-aggregator.test.js
  test/unit/parsed-statement.test.js
Labels: risk: medium, semver: patch

#595 Fixes resolveMx test by using example.com for a valid exchange.
  test/integration/core/dns.tap.js
Labels: risk: low, semver: patch

#594 Bumped grpc-js version to ^1.2.4
  package-lock.json
  package.json
Labels: risk: low, semver: patch

#602 Adds golden-path release note generation script.
  bin/generate-release-notes.js
  bin/github.js
  package-lock.json
  package.json
Labels: risk: low, semver: patch

#603 Adds script to auto-update NEWS.md version header from vNext.
  bin/update-changelog-version.js
  package.json
Labels: risk: low, semver: patch

#604 Adds workflow for publishing to npm when a v* tag is pushed to the repo.
  .github/workflows/publish-release-tag.yml
Labels: risk: low
