Repository newrelic/node-newrelic, pull requests merged in 2022-03, with the labels that each got.

#1109 Allow external versioned testing to run more scenarios
  .eslintrc.js
  test/versioned-external/checkout-external-tests.js
Labels: semver: patch, dev:tests

#1102 added next repo for versioned testing with agent
  test/versioned-external/external-repos.js
Labels: dev:tests

#1113 rely on nock delay instead of mocking http request to timeout in certain cases
  test/integration/pricing/vendor-info-tests.js
Labels: dev:tests

#1110 Add apollo server plugin external tests
  bin/git-commands.js
  test/versioned-external/external-repos.js
Labels: dev:tests

#1119 Remove upper limits
  test/versioned/mysql2/package.json
  test/versioned/restify/restify-post-7/package.json
Labels: dev:tests

#1121 Fix mysql test resource contention
  test/versioned/mysql/basic-pool.tap.js
  test/versioned/mysql/pooling.tap.js
  test/versioned/mysql/setup.js
  test/versioned/mysql/transactions.tap.js
  test/versioned/mysql2/basic-pool.tap.js
  test/versioned/mysql2/pooling.tap.js
  test/versioned/mysql2/setup.js
  test/versioned/mysql2/transaction.tap.js
Labels: dev:tests

#1125 exclude versioned-external from install sub deps when running integration tests
  test/bin/install_sub_deps
Labels: dev:tests

#1124 added link to example repo
  README.md
Labels: documentation

#1134 Adds document porting transaction naming philosophy from forum
  documentation/transaction-naming-philosophy.md
Labels: documentation
