Repository newrelic/node-newrelic, pull requests merged in 2022-12, with the labels that each got.

#1453 NEWRELIC-5565 add versioned tests for Fastify CLM
  test/versioned/fastify/code-level-metrics-hooks.tap.js
  test/versioned/fastify/code-level-metrics-middleware.tap.js
  test/versioned/fastify/package.json
Labels: dev:tests

#1460 docs: update slack invite link
  CONTRIBUTING.md
Labels: documentation

#1459 NEWRELIC-5683 added lockfile checks/linting to CI workflow
  .github/workflows/ci-workflow.yml
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  third_party_manifest.json
Labels: dev:automation

#1469 Update to latest @newrelic/test-utilities
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  third_party_manifest.json
Labels: dev:deps
