Repository newrelic/node-newrelic, pull requests merged in 2022-08, with the labels that each got.

#1311 Bumps minimum external instrumentation modules to new major versions.
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  third_party_manifest.json
Labels: semver: major

#1335 Re-adds minami as a dev dependency.
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  third_party_manifest.json
Labels: dev:deps

#1332 Added unit test suite + integration test
  test/integration/config/index.tap.js
  test/unit/lib/logger.test.js
Labels: dev:tests
