Repository newrelic/node-newrelic, pull requests merged in 2022-02, with the labels that each got.

#1084 added ability to not include PRs that have certain labels
  .github/workflows/notify-release.yml
  bin/pending-prs.js
Labels: dev:automation

#1085 Fixes some npm audit warnings.
  package-lock.json
Labels: risk: low, semver: patch

#1086 Bumps follow-redirects to resolve dev-dependency audit warning.
  package-lock.json
Labels: dev:deps

#1097 Bumps @newrelic/native-metrics to ^7.1.1.
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  third_party_manifest.json
Labels: risk: low, semver: patch

#1098 fixed discuss link in README
  README.md
Labels: documentation
