Repository newrelic/node-newrelic, pull requests merged in 2023-05, with the labels that each got.

#1614 chore: 👋 request lib
  THIRD_PARTY_NOTICES.md
  bin/update-system-config-pages.js
  package-lock.json
  package.json
  test/lib/agent_helper.js
  test/versioned/director/director.tap.js
  test/versioned/express/captures-params.tap.js
  test/versioned/express/ignoring.tap.js
  test/versioned/express/render.tap.js
  test/versioned/express/route-param.tap.js
  test/versioned/express/router-params.tap.js
  test/versioned/fastify/common.js
  test/versioned/hapi/capture-params.tap.js
  test/versioned/hapi/ext.tap.js
  test/versioned/hapi/ignoring.tap.js
  test/versioned/hapi/plugins.tap.js
  test/versioned/hapi/render.tap.js
  test/versioned/hapi/router.tap.js
  test/versioned/hapi/vhost.tap.js
  test/versioned/nestjs/nest.tap.js
  test/versioned/restify/restify-post-7/capture-params.tap.js
  test/versioned/restify/restify-post-7/ignoring.tap.js
  test/versioned/restify/restify-post-7/restify.tap.js
  test/versioned/restify/restify-post-7/router.tap.js
  test/versioned/restify/restify-post-7/rum.tap.js
  test/versioned/restify/restify-post-7/with-express.tap.js
  test/versioned/restify/restify-pre-7/capture-params.tap.js
  test/versioned/restify/restify-pre-7/ignoring.tap.js
  test/versioned/restify/restify-pre-7/restify.tap.js
  test/versioned/restify/restify-pre-7/router.tap.js
  test/versioned/restify/restify-pre-7/rum.tap.js
  third_party_manifest.json
Labels: dev:tests

#1624 chore: remove release-please workflow and scripts
  .github/workflows/release-please.yml
  .release-please-manifest.json
  bin/add-support-statement.js
  bin/test/add-support-statement.test.js
  release-please-config.json
Labels: dev:automation

#1623 ci: add ability to generate release notes from conventional commits
  THIRD_PARTY_NOTICES.md
  bin/conventional-changelog.js
  bin/github.js
  bin/templates/commit.hbs
  bin/templates/header.hbs
  bin/templates/template.hbs
  bin/test/conventional-changelog.test.js
  package-lock.json
  package.json
  third_party_manifest.json
Labels: dev:automation

#1626 test(scripts): fix failing changelog unit test
  bin/test/conventional-changelog.test.js
Labels: dev:tests

#1631 test: pin prisma to < 4.14.0 until we fix instrumentation
  test/versioned/prisma/package.json
Labels: dev:tests

#1628 chore: pin testdobule to 3.17.2 as 3.18.0 no longer works on node 14
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  third_party_manifest.json
Labels: dev:deps

#1635 docs: update Contribution Guide with Conventional Commit info
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#1633 ci: add --use-new-release functionality
  .github/workflows/prep-release.yml
  .github/workflows/prepare-release.yml
  bin/.eslintrc.js
  bin/conventional-changelog.js
  bin/create-docs-pr.js
  bin/prepare-release.js
  bin/templates/header.hbs
  bin/test/conventional-changelog.test.js
  bin/test/create-docs-pr.test.js
  bin/test/prepare-release.test.js
  third_party_manifest.json
Labels: dev:automation

#1638 ci: fix issue with missing type in the prep-release
  .github/workflows/prep-release.yml
Labels: dev:automation

#1640 ci: update to conditionally add CLI flag to prep-release
  .github/workflows/prep-release.yml
Labels: dev:automation

#1641 ci: update prep-release to fetch entire history of caller repo
  .github/workflows/prep-release.yml
Labels: dev:automation

#1649 test: added unit tests for MySQL instrumentation
  lib/instrumentation/mysql/mysql.js
  test/unit/instrumentation/mysql/describePoolQuery.test.js
  test/unit/instrumentation/mysql/describeQuery.test.js
  test/unit/instrumentation/mysql/extractQueryArgs.test.js
  test/unit/instrumentation/mysql/getInstanceParameters.test.js
  test/unit/instrumentation/mysql/index.test.js
  test/unit/instrumentation/mysql/storeDatabaseName.test.js
  test/unit/instrumentation/mysql/wrapCreateConnection.test.js
  test/unit/instrumentation/mysql/wrapCreatePool.test.js
  test/unit/instrumentation/mysql/wrapCreatePoolCluster.test.js
  test/unit/instrumentation/mysql/wrapGetConnection.test.js
  test/unit/instrumentation/mysql/wrapGetConnectionCallback.test.js
  test/unit/instrumentation/mysql/wrapQueryable.test.js
Labels: dev:tests

#1656 chore: update explorer hub link in readme
  README.md
Labels: documentation
