Repository newrelic/node-newrelic, pull requests merged in 2023-08, with the labels that each got.

#1735 feat!: Renamed shim.handleCATHeaders to shim.handleMqTracingHeaders
  lib/shim/message-shim.js
  lib/shim/transaction-shim.js
  test/unit/shim/transaction-shim.test.js
Labels: semver: major

#1731 feat!: updated the default context manager to be AsyncLocalContextManager
  .github/workflows/versioned-coverage.yml
  bin/run-versioned-tests.sh
  documentation/feature-flags.md
  lib/context-manager/create-context-manager.js
  lib/context-manager/diagnostics/legacy-diagnostic-context-manager.js
  lib/feature_flags.js
  lib/instrumentation/core/async-hooks.js
  lib/instrumentation/core/timers.js
  package.json
  test/integration/core/native-promises/async-hooks-new-promise-unresolved.tap.js
  test/integration/core/native-promises/async-hooks.tap.js
  test/integration/core/native-promises/native-promises.js
  test/integration/core/promises.tap.js
  test/integration/core/timers.tap.js
  test/unit/context-manager/create-context-manager.test.js
  test/unit/context-manager/legacy-diagnostic-context-manager.test.js
  test/unit/feature_flag.test.js
  test/unit/instrumentation/core/promises.test.js
  test/unit/instrumentation/prisma-client.test.js
  third_party_manifest.json
Labels: semver: major

#1768 chore: updated next js repo to use main now that the branch has landed
  test/versioned-external/external-repos.js
Labels: dev:tests

#1769 chore: upgraded test utils and removed unused shimmer.patchModule and shimmer.unpatchModule
  THIRD_PARTY_NOTICES.md
  lib/shimmer.js
  package-lock.json
  package.json
  third_party_manifest.json
Labels: dev:tests, dev:deps
