Repository newrelic/node-newrelic, pull requests merged in 2023-04, with the labels that each got.

#1578 added tests for env var and default configuration values for heroku.u…
  test/unit/config/config-defaults.test.js
  test/unit/config/config-env.test.js
Labels: dev:tests

#1580 chore: Add dependabot configuration file to configure conventional commits
  .github/dependabot.yml
Labels: dev:automation

#1586 ci: disable dependabot version updates
  .github/dependabot.yml
Labels: dev:automation

#1592 ci: bump the test utils version to get new makeFullyInstrumented function
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  third_party_manifest.json
Labels: dev:deps

#1520 DO NOT MERGE - set transaction_tracer.record_sql default to obfuscated
  lib/config/default.js
  test/unit/config/config-defaults.test.js
  test/unit/config/config-server-side.test.js
Labels: semver: major

#1591 DO NOT MERGE - Route/URL parameters are now stored on request.parameters.route.* attributes
  lib/serverless/aws-lambda.js
  lib/shim/shim.js
  lib/shim/webframework-shim.js
  lib/transaction/index.js
  test/unit/shim/shim.test.js
  test/unit/shim/webframework-shim.test.js
  test/unit/transaction.test.js
  test/versioned-external/external-repos.js
  test/versioned/express/captures-params.tap.js
  test/versioned/express/router-params.tap.js
  test/versioned/hapi/capture-params.tap.js
  test/versioned/hapi/router.tap.js
  test/versioned/hapi/vhost.tap.js
  test/versioned/restify/restify-post-7/capture-params.tap.js
  test/versioned/restify/restify-post-7/router.tap.js
  test/versioned/restify/restify-pre-7/capture-params.tap.js
  test/versioned/restify/restify-pre-7/router.tap.js
Labels: semver: major

#1563 DO NOT MERGE - Allow registering multiple instrumentation hooks for the same resolved module
  esm-loader.mjs
  lib/instrumentation/@hapi/vision.js
  lib/instrumentation/mysql/mysql.js
  lib/instrumentation/mysql/nr-hooks.js
  lib/shim/conglomerate-shim.js
  lib/shim/datastore-shim.js
  lib/shim/index.js
  lib/shim/message-shim.js
  lib/shim/promise-shim.js
  lib/shim/shim.js
  lib/shim/transaction-shim.js
  lib/shim/webframework-shim.js
  lib/shimmer.js
  lib/symbols.js
  test/integration/api/TestMod.js
  test/integration/api/instrument.tap.js
  test/integration/module-loading/module-loading.tap.js
  test/lib/agent_helper.js
  test/unit/api/api-instrument-loaded-module.test.js
  test/unit/esm-loader.test.mjs
  test/unit/metric/datastore-instance.test.js
  test/unit/shim/datastore-shim.test.js
  test/unit/shim/message-shim.test.js
  test/unit/shim/shim.test.js
  test/unit/shim/webframework-shim.test.js
  test/unit/shimmer.test.js
  test/unit/spans/span-event.test.js
  test/unit/spans/streaming-span-event.test.js
  test/versioned-external/external-repos.js
Labels: risk: high, semver: major

#1600 adds new branch for koa fixes
  README.md
  test/versioned-external/external-repos.js
Labels: dev:tests

#1598 ci: update Snyk generated PR titles to have a Conventional Commit prefix
  .github/workflows/ci-workflow.yml
  .github/workflows/release-please.yml
  .github/workflows/update-snyk-prs.yml
  bin/add-support-statement.js
  bin/test/add-support-statement.test.js
  bin/test/update-snyk-pr.test.js
  bin/update-snyk-pr.js
Labels: dev:automation

#1605 ci: added PR title check automation
  .github/workflows/validate-pr.yml
Labels: dev:automation
