Repository newrelic/node-newrelic, pull requests merged in 2024-01, with the labels that each got.

#1931 test: updated chat-completions tests to properly assert segments
  test/versioned/openai/chat-completions.tap.js
  test/versioned/openai/embeddings.tap.js
Labels: dev:tests

#1935 test: updated abort controller test expected error message based on undici version
  test/versioned/undici/requests.tap.js
Labels: dev:tests

#1937 test: Fix DNS lookup in remote-method test
  test/unit/collector/remote-method.test.js
Labels: dev:tests

#1939 test: removed console log
  test/versioned/openai/chat-completions.tap.js
  test/versioned/openai/embeddings.tap.js
Labels: dev:tests

#1957 chore: Migrated non-sensitive CI values to vars
  .github/workflows/notify-release.yml
  .github/workflows/post-release.yml
Labels: dev:automation

#1976 docs: Fixed jsdoc generation by marking private methods as @private
  api.js
  lib/shim/datastore-shim.js
  lib/shim/message-shim/subscribe-consume.js
  lib/shim/promise-shim.js
  lib/shim/shim.js
  lib/shim/webframework-shim/middleware-mounter.js
  lib/shim/webframework-shim/middleware.js
  lib/transaction/handle.js
  package.json
  third_party_manifest.json
Labels: documentation

#1991 docs: removed documentation around aws_bedrock_instrumentation as feature flag has been removed
  documentation/feature-flags.md
Labels: documentation
