Repository newrelic/node-newrelic, pull requests merged in 2024-04, with the labels that each got.

#2091 chore: Removed scrollbar styling in generated API docs
  jsdoc-conf.json
  package-lock.json
  package.json
Labels: dev:deps

#2106 ci: Updated `prepare-release.js` to not require changelog.json
  .github/workflows/prep-release.yml
  .github/workflows/prepare-release.yml
  bin/prepare-release.js
  bin/test/prepare-release.test.js
Labels: dev:automation

#2119 chore: Updated elastic tests to skip broken version
  test/versioned/elastic/package.json
Labels: dev:automation

#2120 chore: Fixed incorrect pinning of @elastic/transport
  test/versioned/elastic/package.json
Labels: dev:automation

#2124 ci: Removed usage of `use_new_release` from prepare release workflow
  .github/workflows/prep-release.yml
  .github/workflows/prepare-release.yml
  bin/prepare-release.js
Labels: dev:automation

#2135 chore: Fixed versioned security agent CI workflow
  .github/workflows/versioned-security-agent.yml
Labels: dev:automation

#2139 docs: Includes api.js in jsdoc generation
  jsdoc-conf.jsonc
Labels: documentation

#2147 chore: Updated versioned tests to support upcoming tooling
  test/versioned/Readme.md
  test/versioned/amqplib/package.json
  test/versioned/bluebird/package.json
  test/versioned/bunyan/package.json
  test/versioned/cassandra-driver/package.json
  test/versioned/connect/package.json
  test/versioned/director/package.json
  test/versioned/elastic/package.json
  test/versioned/express-esm/package.json
  test/versioned/express/package.json
  test/versioned/fastify/package.json
  test/versioned/generic-pool/package.json
  test/versioned/grpc-esm/package.json
  test/versioned/grpc/package.json
  test/versioned/hapi/package.json
  test/versioned/ioredis/package.json
  test/versioned/langchain/package.json
  test/versioned/mongodb-esm/package.json
  test/versioned/mongodb/package.json
  test/versioned/mysql/package.json
  test/versioned/mysql2/package.json
  test/versioned/nestjs/package.json
  test/versioned/openai/package.json
  test/versioned/pg-esm/package.json
  test/versioned/pg/package.json
  test/versioned/pino/package.json
  test/versioned/prisma/package.json
  test/versioned/redis/package.json
  test/versioned/restify/async-handlers.tap.js
  test/versioned/restify/capture-params.tap.js
  test/versioned/restify/common.js
  test/versioned/restify/ignoring.tap.js
  test/versioned/restify/newrelic.js
  test/versioned/restify/package.json
  test/versioned/restify/pre-7/capture-params.tap.js
  test/versioned/restify/pre-7/ignoring.tap.js
  test/versioned/restify/pre-7/newrelic.js
  test/versioned/restify/pre-7/restify.tap.js
  test/versioned/restify/pre-7/router.tap.js
  test/versioned/restify/pre-7/rum.tap.js
  test/versioned/restify/pre-7/transaction-naming.tap.js
  test/versioned/restify/restify-pre-7/package.json
  test/versioned/restify/restify.tap.js
  test/versioned/restify/router.tap.js
  test/versioned/restify/rum.tap.js
  test/versioned/restify/transaction-naming.tap.js
  test/versioned/restify/with-express.tap.js
  test/versioned/superagent/package.json
  test/versioned/undici/package.json
  test/versioned/winston-esm/package.json
  test/versioned/winston/package.json
Labels: dev:tests

#2172 chore: Made pre-commit hook require dependency changes
  .husky/pre-commit
  bin/update-third-party-notices.sh
Labels: dev:automation

#2174 ci: Updated minimum version of lib-dynamo to work around peer dependency resolution
  test/versioned/aws-sdk-v3/package.json
Labels: dev:tests
