Repository newrelic/node-newrelic, pull requests merged in 2024-10, with the labels that each got.

#2620 test: Migrated `aws-sdk-v2` and `aws-sdk-v3` tests to `node:test`
  test/lib/custom-assertions.js
  test/unit/analytics_events.test.js
  test/unit/attributes.test.js
  test/unit/collector/facts.test.js
  test/unit/environment.test.js
  test/unit/errors/error-collector.test.js
  test/unit/errors/error-event-aggregator.test.js
  test/unit/errors/error-group.test.js
  test/unit/errors/error-trace-aggregator.test.js
  test/unit/errors/server-config.test.js
  test/unit/harvester.test.js
  test/unit/high-security.test.js
  test/unit/index.test.js
  test/unit/instrumentation-tracker.test.js
  test/unit/metrics-mapper.test.js
  test/unit/parse-proc-cpuinfo.test.js
  test/unit/parse-proc-meminfo.test.js
  test/unit/parsed-statement.test.js
  test/unit/priority-queue.test.js
  test/unit/protocols.test.js
  test/unit/serverless/api-gateway-v2.test.js
  test/unit/transaction.test.js
  test/versioned/aws-sdk-v2/amazon-dax-client.tap.js
  test/versioned/aws-sdk-v2/aws-sdk.tap.js
  test/versioned/aws-sdk-v2/dynamodb.tap.js
  test/versioned/aws-sdk-v2/http-services.tap.js
  test/versioned/aws-sdk-v2/instrumentation-supported.tap.js
  test/versioned/aws-sdk-v2/instrumentation-unsupported.tap.js
  test/versioned/aws-sdk-v2/s3.tap.js
  test/versioned/aws-sdk-v2/sns.tap.js
  test/versioned/aws-sdk-v2/sqs.tap.js
  test/versioned/aws-sdk-v3/api-gateway.tap.js
  test/versioned/aws-sdk-v3/bedrock-chat-completions.tap.js
  test/versioned/aws-sdk-v3/bedrock-embeddings.tap.js
  test/versioned/aws-sdk-v3/bedrock-negative-tests.tap.js
  test/versioned/aws-sdk-v3/client-dynamodb.tap.js
  test/versioned/aws-sdk-v3/common.js
  test/versioned/aws-sdk-v3/elasticache.tap.js
  test/versioned/aws-sdk-v3/elb.tap.js
  test/versioned/aws-sdk-v3/lambda.tap.js
  test/versioned/aws-sdk-v3/lib-dynamodb.tap.js
  test/versioned/aws-sdk-v3/rds.tap.js
  test/versioned/aws-sdk-v3/redshift.tap.js
  test/versioned/aws-sdk-v3/rekognition.tap.js
  test/versioned/aws-sdk-v3/s3.tap.js
  test/versioned/aws-sdk-v3/ses.tap.js
  test/versioned/aws-sdk-v3/sns.tap.js
  test/versioned/aws-sdk-v3/sqs.tap.js
Labels: dev:tests

#2624 test: Migrated last group of unit tests to `node:test`
  test/unit/timer.test.js
  test/unit/trace-segment.test.js
  test/unit/tracer.test.js
  test/unit/transaction/trace/index.test.js
  test/unit/transaction/trace/segment.test.js
  test/unit/transaction/trace/trace-aggregator.test.js
  test/unit/transaction/tracer.test.js
Labels: dev:tests

#2623 test: Migrated unit tests to `node:test`
  test/unit/rum.test.js
  test/unit/sampler.test.js
  test/unit/shimmer.test.js
  test/unit/stats.test.js
  test/unit/synthetics.test.js
  test/unit/system-info.test.js
Labels: dev:tests

#2633 docs: Remove SECURITY.md
  SECURITY.md
Labels: documentation

#2636 docs: Updated match custom-assertion jsdoc
  test/lib/custom-assertions.js
Labels: documentation

#2635 test: Migrated bluebird versioned tests to `node:test`
  test/lib/agent_helper.js
  test/lib/promises/common-tests.js
  test/lib/promises/helpers.js
  test/lib/promises/transaction-state.js
  test/versioned/bluebird/common-tests.js
  test/versioned/bluebird/helpers.js
  test/versioned/bluebird/methods.js
  test/versioned/bluebird/methods.tap.js
  test/versioned/bluebird/methods.test.js
  test/versioned/bluebird/package.json
  test/versioned/bluebird/regressions.test.js
  test/versioned/bluebird/transaction-state.tap.js
  test/versioned/bluebird/transaction-state.test.js
  test/versioned/when/package.json
  test/versioned/when/when.tap.js
  test/versioned/when/when.test.js
Labels: dev:tests

#2637 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2632 chore: Migrate `fastify` tests to `node:test`
  test/lib/custom-assertions.js
  test/versioned/fastify/add-hook.tap.js
  test/versioned/fastify/add-hook.test.js
  test/versioned/fastify/code-level-metrics-hooks.tap.js
  test/versioned/fastify/code-level-metrics-hooks.test.js
  test/versioned/fastify/code-level-metrics-middleware.tap.js
  test/versioned/fastify/code-level-metrics-middleware.test.js
  test/versioned/fastify/common.js
  test/versioned/fastify/errors.test.js
  test/versioned/fastify/fastify-2-naming.tap.js
  test/versioned/fastify/fastify-2-naming.test.js
  test/versioned/fastify/fastify-3-naming.tap.js
  test/versioned/fastify/fastify-3.tap.js
  test/versioned/fastify/fastify-gte3-naming.test.js
  test/versioned/fastify/fastify-gte3.test.js
  test/versioned/fastify/naming-common.js
  test/versioned/fastify/new-state-tracking.tap.js
  test/versioned/fastify/new-state-tracking.test.js
  test/versioned/fastify/package.json
Labels: dev:tests

#2638 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2634 chore: Migrate `bunyan`, `pino`, and `winston` tests to `node:test`
  test/lib/logging-helper.js
  test/versioned/bunyan/bunyan.tap.js
  test/versioned/bunyan/bunyan.test.js
  test/versioned/bunyan/helpers.js
  test/versioned/bunyan/package.json
  test/versioned/pino/helpers.js
  test/versioned/pino/package.json
  test/versioned/pino/pino.tap.js
  test/versioned/pino/pino.test.js
  test/versioned/winston-esm/package.json
  test/versioned/winston-esm/winston.test.mjs
  test/versioned/winston/helpers.js
  test/versioned/winston/package.json
  test/versioned/winston/winston.tap.js
  test/versioned/winston/winston.test.js
Labels: dev:tests

#2641 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2665 ci: Added delay to site extension publishing to wait for NPM
  .github/workflows/azure-site-extension.yml
Labels: dev:automation

#2670 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2673 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2679 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2678 chore: Updated cassandra-driver tests to node:test
  test/versioned/cassandra-driver/package.json
  test/versioned/cassandra-driver/query.tap.js
  test/versioned/cassandra-driver/query.test.js
Labels: dev:tests
