Repository newrelic/node-newrelic, pull requests merged in 2024-09, with the labels that each got.

#2537 docs: Updated Next.js Otel cloud provider FAQ
  documentation/nextjs/faqs/cloud-providers.md
Labels: documentation

#2538 docs: Updated formatting of cloud-providers.md
  documentation/nextjs/faqs/cloud-providers.md
Labels: documentation

#2541 chore: Added a match function for tests
  test/lib/custom-assertions.js
Labels: dev:tests

#2510 chore: Converted collector unit tests to node:test
  lib/collector/api.js
  test/lib/assert-metrics.js
  test/lib/test-collector.js
  test/unit/collector/api-connect.test.js
  test/unit/collector/api-login.test.js
  test/unit/collector/api-run-lifecycle.test.js
  test/unit/collector/api.test.js
  test/unit/collector/http-agents.test.js
  test/unit/collector/key-parser.test.js
  test/unit/collector/parse-response.test.js
  test/unit/collector/remote-method.test.js
  test/unit/collector/serverless.test.js
Labels: dev:tests

#2535 test: Converted `llm-events` tests to use `node:test`
  test/unit/llm-events/aws-bedrock/bedrock-command.test.js
  test/unit/llm-events/aws-bedrock/bedrock-response.test.js
  test/unit/llm-events/aws-bedrock/chat-completion-message.test.js
  test/unit/llm-events/aws-bedrock/chat-completion-summary.test.js
  test/unit/llm-events/aws-bedrock/embedding.test.js
  test/unit/llm-events/aws-bedrock/error.test.js
  test/unit/llm-events/aws-bedrock/event.test.js
  test/unit/llm-events/aws-bedrock/stream-handler.test.js
  test/unit/llm-events/error.test.js
  test/unit/llm-events/feedback-message.test.js
  test/unit/llm-events/langchain/chat-completion-message.test.js
  test/unit/llm-events/langchain/chat-completion-summary.test.js
  test/unit/llm-events/langchain/event.test.js
  test/unit/llm-events/langchain/tool.test.js
  test/unit/llm-events/langchain/vector-search-result.test.js
  test/unit/llm-events/langchain/vector-search.test.js
  test/unit/llm-events/openai/chat-completion-message.test.js
  test/unit/llm-events/openai/chat-completion-summary.test.js
  test/unit/llm-events/openai/embedding.test.js
Labels: dev:tests

#2540 chore: Converted errors unit tests to node:test
  lib/config/index.js
  test/unit/errors/error-collector.test.js
  test/unit/errors/error-event-aggregator.test.js
  test/unit/errors/error-group.test.js
  test/unit/errors/error-trace-aggregator.test.js
  test/unit/errors/expected.test.js
  test/unit/errors/ignore.test.js
  test/unit/errors/server-config.test.js
Labels: dev:tests

#2546 test: Migrated `test/unit/util` to use `node:test`
  test/unit/util/application-logging.test.js
  test/unit/util/async-each-limit.test.js
  test/unit/util/byte-limit.test.js
  test/unit/util/camel-case.test.js
  test/unit/util/code-level-metrics.test.js
  test/unit/util/codec.test.js
  test/unit/util/hashes.test.js
  test/unit/util/label-parser.test.js
  test/unit/util/llm-utils.test.js
  test/unit/util/logger.test.js
  test/unit/util/obfuscate-sql.test.js
  test/unit/util/objects.test.js
  test/unit/util/snake-case.test.js
Labels: dev:tests

#2553 chore: Disable express@5 in versioned tests
  test/versioned/express-esm/package.json
  test/versioned/express/package.json
Labels: dev:tests

#2554 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2556 test: Migrated `test/unit/spans` to use `node:test`
  test/unit/spans/base-span-streamer.test.js
  test/unit/spans/batch-span-streamer.test.js
  test/unit/spans/create-span-event-aggregator.test.js
  test/unit/spans/map-to-streaming-type.test.js
  test/unit/spans/span-event-aggregator.test.js
  test/unit/spans/span-event.test.js
  test/unit/spans/span-streamer.test.js
  test/unit/spans/streaming-span-attributes.test.js
  test/unit/spans/streaming-span-event-aggregator.test.js
  test/unit/spans/streaming-span-event.test.js
Labels: dev:tests

#2557 fix: Nuget pack generates packagName.semver and not packageName-semver
  .github/workflows/azure-site-extension.yml
Labels: dev:automation

#2561 chore: Document emitted events
  lib/agent.js
  lib/aggregators/base-aggregator.js
  lib/collector/api.js
  lib/config/index.js
  lib/errors/error-collector.js
  lib/harvester.js
  lib/metrics/normalizer.js
  lib/spans/streaming-span-event-aggregator.js
  lib/transaction/index.js
  lib/transaction/transaction-event-aggregator.js
  lib/util/stream-sink.js
  test/integration/newrelic-harvest-limits.tap.js
  test/integration/newrelic-response-handling.tap.js
  test/unit/aggregators/base-aggregator.test.js
  test/unit/collector/api.test.js
  test/unit/harvester.test.js
  test/unit/trace-aggregator.test.js
  test/unit/transaction-event-aggregator.test.js
Labels: documentation

#2552 test: Convert `metric` and `metrics-recorder` tests to `node:test`
  test/lib/custom-assertions.js
  test/unit/metric/datastore-instance.test.js
  test/unit/metric/metric-aggregator.test.js
  test/unit/metric/metrics.test.js
  test/unit/metric/normalizer-rule.test.js
  test/unit/metric/normalizer-tx-segment.test.js
  test/unit/metric/normalizer.test.js
  test/unit/metrics-recorder/distributed-trace.test.js
  test/unit/metrics-recorder/generic.test.js
  test/unit/metrics-recorder/http-external.test.js
  test/unit/metrics-recorder/http.test.js
  test/unit/metrics-recorder/queue-time-http.test.js
Labels: dev:tests

#2564 fix: Ensure Readme displays for Azure site extension
  cloud-tooling/README.md
  cloud-tooling/azure-site-extension/NewRelic.Azure.WebSites.Extension.NodeAgent.nuspec
Labels: dev:automation

#2549 chore: Updated serverless unit tests to node:test
  THIRD_PARTY_NOTICES.md
  package.json
  test/lib/temp-override-uncaught.js
  test/lib/temp-remove-listeners.js
  test/unit/serverless/api-gateway-v2.test.js
  test/unit/serverless/aws-lambda.test.js
  third_party_manifest.json
Labels: dev:tests

#2568 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2570 chore: Migrate block of unit tests to `node:test`
  test/unit/adaptive-sampler.test.js
  test/unit/analytics_events.test.js
  test/unit/apdex.test.js
  test/unit/attributes.test.js
Labels: dev:tests

#2572 chore: Migrate second block of unit tests to `node:test`
  test/unit/db_util.test.js
  test/unit/environment.test.js
  test/unit/error_events.test.js
Labels: dev:tests

#2575 ci: Added workflow run trigger to Azure site extension publish job
  .github/workflows/azure-site-extension.yml
Labels: dev:automation

#2580 test: Removed transitive deps from versioned tests as they will auto-install if required as peer deps
  test/versioned/aws-sdk-v2/package.json
  test/versioned/aws-sdk-v3/package.json
  test/versioned/grpc/package.json
  test/versioned/langchain/package.json
  test/versioned/nextjs/package.json
  test/versioned/prisma/package.json
Labels: dev:tests

#2578 test: Updated koa-router to tests to handle bug fixes from 13.0.1
  test/versioned/koa/package.json
  test/versioned/koa/router-common.js
Labels: dev:tests

#2582 test: Updated a missing `minSupported` in aws-sdk-v3 versioned tests
  test/versioned/aws-sdk-v3/package.json
Labels: dev:tests

#2581 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2583 chore: Removed noisy test log
  test/unit/util/obfuscate-sql.test.js
Labels: dev:tests

#2584 test: Updated fastify versioned tests to work with `fastify@5.0.0`
  test/versioned/fastify/add-hook.tap.js
  test/versioned/fastify/code-level-metrics-hooks.tap.js
  test/versioned/fastify/code-level-metrics-middleware.tap.js
  test/versioned/fastify/errors.tap.js
  test/versioned/fastify/naming-common.js
  test/versioned/fastify/new-state-tracking.tap.js
Labels: dev:tests

#2587 test: Fixed @koa/router tests. path-to-regex differs between @koa/router and koa-router now
  test/versioned/koa/router-common.js
Labels: dev:tests

#2588 test: Updated how we handle the koa-router nuance of wildcard routes
  test/versioned/koa/package.json
  test/versioned/koa/router-common.js
Labels: dev:tests

#2589 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2601 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2599 test: Migrated `test/unit/shim` to `node:test`
  test/lib/custom-assertions.js
  test/unit/shim/conglomerate-shim.test.js
  test/unit/shim/datastore-shim.test.js
  test/unit/shim/message-shim.test.js
  test/unit/shim/promise-shim.test.js
  test/unit/shim/shim.test.js
  test/unit/shim/transaction-shim.test.js
  test/unit/shim/webframework-shim.test.js
Labels: dev:tests

#2607 chore: Migrate block of unit tests to `node:test`
  test/lib/temp-remove-listeners.js
  test/unit/load-externals.test.js
  test/unit/logger.test.js
  test/unit/metrics-mapper.test.js
  test/unit/name-state.test.js
  test/unit/parse-proc-cpuinfo.test.js
  test/unit/parse-proc-meminfo.test.js
  test/unit/parsed-statement.test.js
  test/unit/prioritized-attributes.test.js
  test/unit/priority-queue.test.js
  test/unit/protocols.test.js
Labels: dev:tests

#2604 chore: Migrate block of unit tests to node:test
  test/unit/index.test.js
  test/unit/instrumentation-descriptor.test.js
  test/unit/instrumentation-tracker.test.js
  test/unit/util/is-absolute-path.test.js
Labels: dev:tests

#2610 test: Updated tests that relied on `tspl` by awating the `plan.completed` instead of calling `end` to avoid flaky tests
  test/unit/serverless/api-gateway-v2.test.js
  test/unit/serverless/aws-lambda.test.js
  test/unit/shim/message-shim.test.js
  test/unit/shim/shim.test.js
  test/versioned/express/app-use.test.js
  test/versioned/express/bare-router.test.js
  test/versioned/express/errors.test.js
  test/versioned/express/express-enrouten.test.js
  test/versioned/express/ignoring.test.js
  test/versioned/express/issue171.test.js
  test/versioned/express/render.test.js
  test/versioned/express/route-iteration.test.js
  test/versioned/express/route-param.test.js
  test/versioned/express/router-params.test.js
  test/versioned/express/transaction-naming.test.js
Labels: dev:tests

#2612 test: Migrated `test/versioned/amqplib` to `node:test`
  test/versioned/amqplib/amqp-utils.js
  test/versioned/amqplib/callback.test.js
  test/versioned/amqplib/package.json
  test/versioned/amqplib/promises.tap.js
  test/versioned/amqplib/promises.test.js
Labels: dev:tests

#2616 test: Updated the mininum version of pg-native in pg-esm tests to align with the pg tests
  THIRD_PARTY_NOTICES.md
  package.json
  test/versioned/pg-esm/package.json
  third_party_manifest.json
Labels: dev:tests

#2614 docs: Updated compatibility report
  compatibility.md
Labels: documentation
