Repository newrelic/node-newrelic, pull requests merged in 2024-05, with the labels that each got.

#2183 chore: Added workflow for generating compatibility doc
  .github/workflows/compatibility-report.yml
Labels: dev:automation

#2186 chore: Updated validate-pr workflow
  .github/workflows/validate-pr.yml
Labels: dev:automation

#2188 chore: Fixed conditionals in CI workflow
  .github/workflows/ci-workflow.yml
Labels: dev:automation

#2190 chore: Fixed superagent versioned tests
  test/versioned/superagent/async-await.tap.js
  test/versioned/superagent/superagent.tap.js
  test/versioned/superagent/test-server.js
Labels: dev:tests

#2211 chore: Fixed aws-sdk-v3 bedrock tests
  test/versioned/aws-sdk-v3/bedrock-chat-completions.tap.js
Labels: dev:tests

#2212 chore: Fixed aws-sdk-v3 bedrock tests (again)
  test/versioned/aws-sdk-v3/bedrock-chat-completions.tap.js
Labels: dev:tests

#2215 chore: Fixed CI jobs
  .github/workflows/ci-workflow.yml
  .github/workflows/compatibility-report.yml
Labels: dev:automation

#2216 test: Updated langchain versioned tests to separate the vectorstore and other tests. This is to avoid peer resolution of `@langchain/community` package that is being used to test the elasticsearch vectorstore
  test/versioned/langchain/package.json
Labels: dev:tests

#2223 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2226 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2230 test: Updated ioredis tests to assert the host metric getting created on ioredis calls
  test/versioned/ioredis/ioredis-3.tap.js
  test/versioned/ioredis/ioredis.tap.js
Labels: dev:tests

#2233 test: Ported `when` and `q` integration tests to versioned tests
  THIRD_PARTY_NOTICES.md
  package.json
  test/versioned/q/newrelic.js
  test/versioned/q/package.json
  test/versioned/q/q.tap.js
  test/versioned/when/newrelic.js
  test/versioned/when/package.json
  test/versioned/when/when.tap.js
  third_party_manifest.json
Labels: dev:tests

#2231 test: Migrated `memcached` tests to versioned tests
  .github/workflows/ci-workflow.yml
  package.json
  test/lib/agent_helper.js
  test/versioned/memcached/memcached.tap.js
  test/versioned/memcached/newrelic.js
  test/versioned/memcached/package.json
Labels: dev:tests

#2234 docs: Updated compatibility report
  compatibility.md
Labels: documentation
