Repository newrelic/node-newrelic, pull requests merged in 2024-07, with the labels that each got.

#2327 docs: included commands and links for mac setup
  documentation/developer-setup.md
Labels: documentation

#2329 chore: Fixed copy paste error in post release workflow
  .github/workflows/post-release.yml
Labels: dev:automation

#2334 fix: Refactored benchmark tests to complete async functions
  test/benchmark/datastore-shim/test-datastore.js
  test/benchmark/promises/shared.js
  test/lib/benchmark.js
Labels: dev:tests

#2338 test: Fixed recordMiddlewawre benchmark test
  test/benchmark/datastore-shim/shared.js
  test/benchmark/shim/record.bench.js
  test/benchmark/shim/row-callbacks.bench.js
  test/benchmark/shim/segments.bench.js
  test/benchmark/webframework-shim/recordMiddleware.bench.js
Labels: dev:tests

#2342 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2345 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2341 chore: Always upload status logs in compat report CI
  .github/workflows/compatibility-report.yml
Labels: dev:automation

#2346 ci: increase the limit of installs from 2 to a bigger number
  bin/run-versioned-tests.sh
Labels: dev:automation

#2353 ci: Changed the default project idea for our org board
  .github/workflows/board.yml
Labels: dev:automation

#2357 ci: Updated board workflow to use new graphql calls to add items to project board
  .github/workflows/board.yml
Labels: dev:automation

#2360 ci: Fixed issue with obtaining node id for issues in add-to-board
  .github/workflows/board.yml
Labels: dev:automation

#2362 ci: Fixed syntax issue with parsing jq
  .github/workflows/board.yml
Labels: dev:automation

#2350 test: Updated benchmark test results to output result files
  .gitignore
  bin/compare-bench-results.js
  bin/run-bench.js
  test/benchmark/async-hooks.bench.js
  test/benchmark/datastore-shim/recordBatch.bench.js
  test/benchmark/datastore-shim/recordOperation.bench.js
  test/benchmark/datastore-shim/recordQuery.bench.js
  test/benchmark/datastore-shim/test-datastore.js
  test/benchmark/http/server.bench.js
  test/benchmark/promises/native.bench.js
  test/benchmark/promises/shared.js
  test/lib/benchmark.js
Labels: dev:tests

#2368 refactor: consolidated adding issue/pr to board and assigning the appropriate status into 1 step
  .github/workflows/board.yml
Labels: dev:automation

#2370 refactor: fixed syntax error with add to board workflow
  .github/workflows/board.yml
Labels: dev:automation

#2371 chore: fix board refactor
  .github/workflows/board.yml
Labels: dev:automation

#2366 ci: Added benchmark test GitHub Action
  .github/workflows/benchmark-tests.yml
  bin/run-bench.js
Labels: dev:automation

#2372 test: Removed server.start in grpc tests as it is deprecated and no longer needed
  test/integration/grpc/reconnect.tap.js
  test/integration/infinite-tracing-connection.tap.js
Labels: dev:tests

#2374 ci: Include date created when adding new issue/pr to board
  .github/workflows/board.yml
Labels: dev:automation

#2375 ci: Pin Node 22 to 22.4.1
  .github/workflows/benchmark-tests.yml
  .github/workflows/ci-workflow.yml
  .github/workflows/smoke-test-workflow.yml
  .github/workflows/versioned-coverage.yml
  .github/workflows/versioned-security-agent.yml
Labels: dev:automation

#2383 chore: Reverted "ci: Pin Node 22 to 22.4.1"
  .github/workflows/benchmark-tests.yml
  .github/workflows/ci-workflow.yml
  .github/workflows/smoke-test-workflow.yml
  .github/workflows/versioned-coverage.yml
  .github/workflows/versioned-security-agent.yml
Labels: dev:automation

#2392 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2400 chore: Verified MySQL host:port metric is recorded
  test/versioned/mysql/basic.tap.js
  test/versioned/mysql2/basic.tap.js
Labels: dev:tests

#2401 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2387 chore: Switch to using Node built-in test runner
  THIRD_PARTY_NOTICES.md
  package.json
  test/lib/test-reporter.mjs
  third_party_manifest.json
Labels: dev:tests

#2416 test: Removed mongodb-esm tests as they are not atomic and conflicting with mongodb tests in CI
  test/versioned/mongodb-esm/bulk.tap.mjs
  test/versioned/mongodb-esm/collection-common.mjs
  test/versioned/mongodb-esm/collection-find.tap.mjs
  test/versioned/mongodb-esm/collection-index.tap.mjs
  test/versioned/mongodb-esm/collection-misc.tap.mjs
  test/versioned/mongodb-esm/collection-update.tap.mjs
  test/versioned/mongodb-esm/common.cjs
  test/versioned/mongodb-esm/cursor.tap.mjs
  test/versioned/mongodb-esm/db.tap.mjs
  test/versioned/mongodb-esm/newrelic.cjs
  test/versioned/mongodb-esm/package.json
Labels: dev:tests

#2415 docs: Updated compatibility report
  compatibility.md
Labels: documentation
