Repository newrelic/node-newrelic, pull requests merged in 2024-06, with the labels that each got.

#2240 chore: Updated readme to remove no longer relevant information
  README.md
Labels: documentation

#2241 chore: Updated flaky when test
  test/versioned/when/when.tap.js
Labels: dev:tests

#2255 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2249 chore: Added AI support docs for automation
  .github/workflows/compatibility-report.yml
  ai-support.json
  ai-support.spec.md
Labels: dev:automation

#2259 chore: Updated versioned security agent workflow with simpler setup
  .github/workflows/versioned-security-agent.yml
Labels: dev:automation

#2262 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2261 chore: Added a missing library we instrument to be picked up by the compatibility report
  test/versioned/aws-sdk-v3/package.json
Labels: documentation

#2264 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2267 chore: Added a script that generates Dashboard json for reporting on libraries by version
  dashboards/constants.js
  dashboards/generate-library-usage.js
  dashboards/library-usage.json
  dashboards/utils.js
Labels: dev:automation

#2271 ci: Updated security agent workflow to use large runners when available
  .github/workflows/versioned-security-agent.yml
Labels: dev:automation

#2273 ci: Added ability to run a build step in create release
  .github/workflows/release-creation.yml
Labels: dev:automation

#2272 chore: Updated GitHub Actions versions
  .github/workflows/ci-workflow.yml
  .github/workflows/notify-release.yml
  .github/workflows/post-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-branch.yml
  .github/workflows/release-creation.yml
  .github/workflows/repolinter.yml
  .github/workflows/smoke-test-workflow.yml
  .github/workflows/update-snyk-prs.yml
  .github/workflows/validate-pr.yml
  .github/workflows/versioned-coverage.yml
  .github/workflows/versioned-security-agent.yml
Labels: dev:automation

#2283 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2285 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2290 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2294 test: fixed log error stack message truncating and failing equality test
  test/unit/api/api-record-log-events.test.js
Labels: dev:tests

#2281 test: Updated shimmer method in benchmark tests
  test/benchmark/http/server.bench.js
  test/benchmark/shimmer/instrumentation.bench.js
  test/lib/benchmark.js
Labels: dev:tests

#2299 test: Updated undici versioned tests to assert an error is present and not the actual message
  test/versioned/undici/requests.tap.js
Labels: dev:tests

#2298 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2309 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2307 chore: Forced re-creation of API docs on gh-pages
  bin/publish-docs.sh
Labels: dev:automation

#2316 ci: Added Node 22 to smoke tests and nightly versioned test runs
  .github/workflows/smoke-test-workflow.yml
  .github/workflows/versioned-coverage.yml
  .github/workflows/versioned-security-agent.yml
Labels: dev:automation

#2318 docs: Updated compatibility report
  compatibility.md
Labels: documentation
