Repository newrelic/node-newrelic, pull requests merged in 2024-08, with the labels that each got.

#2422 docs: Updated examples to properly use specs
  examples/shim/Datastore-Simple.md
  examples/shim/Messaging-Simple.md
  examples/shim/Webframework-Simple.md
Labels: documentation

#2433 fix: typo in doc header
  documentation/nextjs/faqs/error-handling.md
Labels: documentation

#2435 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2438 test: Moved pkgVersion to collection-common to avoid a conflict with ESM tests
  test/versioned/mongodb/collection-common.js
  test/versioned/mongodb/collection-misc.tap.js
  test/versioned/mongodb/collection-update.tap.js
  test/versioned/mongodb/common.js
Labels: dev:tests

#2439 chore: Limited superagent tests to avoid new breaking release
  test/versioned/superagent/package.json
Labels: dev:tests

#2444 chore: Fixed mongodb-esm tests in combination with security agent
  test/versioned/mongodb-esm/bulk.tap.mjs
  test/versioned/mongodb-esm/bulk.test.mjs
  test/versioned/mongodb-esm/collection-common.mjs
  test/versioned/mongodb-esm/collection-find.tap.mjs
  test/versioned/mongodb-esm/collection-find.test.mjs
  test/versioned/mongodb-esm/collection-index.tap.mjs
  test/versioned/mongodb-esm/collection-index.test.mjs
  test/versioned/mongodb-esm/collection-misc.tap.mjs
  test/versioned/mongodb-esm/collection-misc.test.mjs
  test/versioned/mongodb-esm/collection-update.tap.mjs
  test/versioned/mongodb-esm/collection-update.test.mjs
  test/versioned/mongodb-esm/cursor.tap.mjs
  test/versioned/mongodb-esm/cursor.test.mjs
  test/versioned/mongodb-esm/db.tap.mjs
  test/versioned/mongodb-esm/db.test.mjs
  test/versioned/mongodb-esm/package.json
  test/versioned/mongodb-esm/test-assertions.mjs
  test/versioned/mongodb-esm/test-hooks.mjs
  test/versioned/mongodb/common.js
Labels: dev:tests

#2440 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2450 chore: Remove promise resolvers from callback based agent unit tests
  test/unit/agent/agent.test.js
  test/unit/agent/synthetics.test.js
Labels: dev:tests

#2452 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2456 chore: Removed limit on superagent versioned testing
  test/versioned/superagent/package.json
Labels: dev:tests

#2460 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2474 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2478 test: Skip `@koa/router@13.0.0` because of failures
  test/versioned/koa/package.json
Labels: dev:tests

#2480 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2479 docs: Remove reference to @newrelic/next in README
  README.md
Labels: documentation

#2481 chore: Updated aggregators unit tests to node:test
  test/unit/aggregators/base-aggregator.test.js
  test/unit/aggregators/event-aggregator.test.js
  test/unit/aggregators/log-aggregator.test.js
Labels: dev:tests

#2487 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2490 ci: Updated codecov action sha to post coverage from forks. Added flag to fail ci if it fails to upload report
  .github/workflows/ci-workflow.yml
Labels: dev:automation

#2497 chore: Fixed linting scripts
  package.json
Labels: dev:automation

#2493 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2508 chore: Converted context-manager unit tests to node:test
  test/unit/context-manager/async-local-context-manager.test.js
  test/unit/context-manager/context-manager-tests.js
  test/unit/context-manager/create-context-manager.test.js
Labels: dev:tests

#2524 docs: cleaned up formatting of api.js to properly inject example snippets when rendering on API docs site
  api.js
Labels: documentation

#2523 docs: Updated compatibility report
  compatibility.md
Labels: documentation
