Repository newrelic/node-newrelic, pull requests merged in 2025-08, with the labels that each got.

#3277 test: Fixed CI issues with latest 24
  test/integration/instrumentation/http-outbound.test.js
  test/lib/fake-cert.js
  test/versioned/prisma/setup.js
Labels: dev:tests

#3286 chore: Remove diacritical grave encoding
  bin/pending-prs.js
Labels: dev:automation, dev:repo_maintenance

#3299 docs: Updated compatibility report
  compatibility.md
Labels: documentation, dev:repo_maintenance

#3304 docs: Updated compatibility report
  compatibility.md
Labels: documentation, dev:repo_maintenance

#3313 docs: Updated compatibility report
  compatibility.md
Labels: documentation, dev:repo_maintenance

#3335 docs: Updated compatibility report
  compatibility.md
Labels: documentation, dev:repo_maintenance

#3332 ci: default the benchmark host to staging
  bin/otel-metrics-sender.js
  dashboards/benchmark-test-metrics.json
  test/benchmark/Readme.md
Labels: dev:tests

#3244 chore: Refactor OTEL bridge signals setup
  lib/otel/logs/bootstrap-logs.js
  lib/otel/logs/index.js
  lib/otel/metrics/bootstrap-metrics.js
  lib/otel/metrics/index.js
  lib/otel/segments/index.js
  lib/otel/setup-signal.js
  lib/otel/setup.js
  lib/otel/traces/attr-reconciler.js
  lib/otel/traces/constants.js
  lib/otel/traces/exception-mapping.js
  lib/otel/traces/index.js
  lib/otel/traces/rules.js
  lib/otel/traces/sampler.js
  lib/otel/traces/segment-synthesis.js
  lib/otel/traces/segments/consumer.js
  lib/otel/traces/segments/database.js
  lib/otel/traces/segments/http-external.js
  lib/otel/traces/segments/index.js
  lib/otel/traces/segments/internal.js
  lib/otel/traces/segments/producer.js
  lib/otel/traces/segments/server.js
  lib/otel/traces/segments/utils.js
  lib/otel/traces/span-processor.js
  lib/otel/traces/transformation-rules.json
  lib/otel/traces/utils.js
  test/unit/lib/otel/exception-mapping.test.js
  test/unit/lib/otel/fixtures/consumer.js
  test/unit/lib/otel/fixtures/db-sql.js
  test/unit/lib/otel/fixtures/http-client.js
  test/unit/lib/otel/fixtures/producer.js
  test/unit/lib/otel/fixtures/server.js
  test/unit/lib/otel/logs/index.test.js
  test/unit/lib/otel/metrics/index.test.js
  test/unit/lib/otel/rules.test.js
  test/unit/lib/otel/sampler.test.js
  test/unit/lib/otel/segment-synthesizer.test.js
  test/unit/lib/otel/segment-utils.test.js
  test/versioned/otel-bridge/span.test.js
Labels: dev:repo_maintenance

#3338 test: Hardened `batch-span-streamer.test.js` to avoid random failures in CI
  test/unit/spans/batch-span-streamer.test.js
Labels: dev:tests

#3342 ci: Updated the redis container to use the official `redis` image as `bitnami/redis` is moving and no reason to use a 3rd party image
  docker-compose.yml
Labels: dev:automation
