Repository newrelic/node-newrelic, pull requests merged in 2025-06, with the labels that each got.

#3131 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#3149 test: Skips running nest 11+ on node 18 due to dropping support
  test/versioned/nestjs/package.json
Labels: dev:tests

#3160 chore: Improved output of pending prs script
  .github/workflows/compatibility-report.yml
  bin/pending-prs.js
Labels: dev:repo_maintenance

#3168 test: unpinned google genai tests
  test/versioned/google-genai/package.json
Labels: dev:tests

#3171 docs: Updated compatibility report
  compatibility.md
Labels: documentation, dev:repo_maintenance

#3174 docs: Updated compatibility report
  compatibility.md
Labels: documentation, dev:repo_maintenance

#3178 ci: Fixed the name of todo colum in add to board reusable workflow
  .github/workflows/board.yml
Labels: dev:automation

#3182 docs: Updated compatibility report
  compatibility.md
Labels: documentation, dev:repo_maintenance

#3185 chore: Updated undici tests to unblock CI
  test/versioned/undici/package.json
Labels: dev:tests

#3190 docs: Updated compatibility report
  compatibility.md
Labels: documentation, dev:repo_maintenance
