Repository newrelic/node-newrelic, pull requests merged in 2025-05, with the labels that each got.

#3075 chore: Tweaked redis pin
  test/versioned/redis/package.json
Labels: dev:tests

#3074 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#3094 chore: Pins security agent due to bug
  THIRD_PARTY_NOTICES.md
  package.json
  third_party_manifest.json
Labels: dependencies

#3082 chore: Added support for running jobs on label
  .github/workflows/ci-workflow.yml
  .github/workflows/smoke-test-workflow.yml
  .github/workflows/versioned-security-agent.yml
Labels: dev:automation

#3122 chore: Pinned openai due to new major
  lib/instrumentation/openai.js
  test/versioned/openai/package.json
Labels: dev:tests
