Repository newrelic/node-newrelic, pull requests merged in 2025-07, with the labels that each got.

#3225 docs: restore removal of enty/exit spans feature
  NEWS.md
Labels: documentation

#3234 test: Updated tests to mock outgoing calls to avoid issues in CI
  test/integration/instrumentation/http-outbound.test.js
  test/unit/spans/span-event.test.js
Labels: dev:tests

#3237 docs: Updated compatibility report
  compatibility.md
Labels: documentation, dev:repo_maintenance

#3097 feat!: Dropped support for Node.js 18
  .github/workflows/benchmark-tests.yml
  .github/workflows/ci-workflow.yml
  .github/workflows/smoke-test-workflow.yml
  .github/workflows/versioned-security-agent.yml
  THIRD_PARTY_NOTICES.md
  lib/environment.js
  package.json
  test/integration/uninstrumented/package.json
  test/unit/environment.test.js
  test/unit/util/hashes.test.js
  test/versioned/amqplib-esm/package.json
  test/versioned/amqplib/package.json
  test/versioned/aws-sdk-v2/package.json
  test/versioned/aws-sdk-v3/package.json
  test/versioned/azure-functions/package.json
  test/versioned/bluebird/package.json
  test/versioned/bunyan/package.json
  test/versioned/cassandra-driver/package.json
  test/versioned/cls/package.json
  test/versioned/connect/package.json
  test/versioned/disabled-instrumentation/package.json
  test/versioned/elastic/package.json
  test/versioned/esm-package/package.json
  test/versioned/express-esm/package.json
  test/versioned/express/package.json
  test/versioned/fastify/package.json
  test/versioned/generic-pool/package.json
  test/versioned/grpc-esm/package.json
  test/versioned/grpc/package.json
  test/versioned/hapi/package.json
  test/versioned/ioredis/package.json
  test/versioned/kafkajs/package.json
  test/versioned/koa/package.json
  test/versioned/langchain/package.json
  test/versioned/memcached/package.json
  test/versioned/mongodb-esm/package.json
  test/versioned/mongodb/package.json
  test/versioned/mysql/package.json
  test/versioned/mysql2/package.json
  test/versioned/nestjs/package.json
  test/versioned/nextjs/package.json
  test/versioned/openai/package.json
  test/versioned/opensearch/package.json
  test/versioned/otel-bridge/package.json
  test/versioned/pg-esm/package.json
  test/versioned/pg/package.json
  test/versioned/pino/package.json
  test/versioned/prisma/package.json
  test/versioned/q/package.json
  test/versioned/redis/package.json
  test/versioned/restify/package.json
  test/versioned/superagent/package.json
  test/versioned/undici/package.json
  test/versioned/when/package.json
  test/versioned/winston-esm/package.json
  test/versioned/winston/package.json
  third_party_manifest.json
Labels: dev:automation

#3256 ci: Fail benchmark ci if tests fail
  bin/run-bench.js
Labels: dev:tests

#3259 test: pin nestjs to avoid failure with cli
  test/versioned/nestjs/package.json
  test/versioned/nestjs/test-app-replacements/app.controller.ts
Labels: dev:tests

#3258 test: Fix failing http benchmark test
  test/benchmark/http/server.bench.js
Labels: dev:tests

#3260 test: cleaned up engines and version ranges in versioned tests
  test/versioned/aws-sdk-v3/package.json
  test/versioned/google-genai/package.json
  test/versioned/mongodb-esm/package.json
  test/versioned/pg-esm/package.json
  test/versioned/pg/package.json
  test/versioned/undici/package.json
Labels: dev:tests

#3265 docs: Updated compatibility report
  compatibility.md
Labels: documentation, dev:repo_maintenance

#3267 docs: Updated compatibility report
  compatibility.md
Labels: documentation, dev:repo_maintenance

#3269 test: force install of peer deps on nestjs test app
  test/versioned/nestjs/setup.js
Labels: dev:tests
