Repository newrelic/node-newrelic, pull requests merged in 2025-01, with the labels that each got.

#2855 chore: Cherry pick mysql2 fix to next branch
  test/versioned/mysql2/promises.test.js
Labels: dev:tests

#2856 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2858 test: Removed `t.diagnostic` from tests
  test/integration/distributed-tracing/trace-context-cross-agent.test.js
  test/integration/uninstrumented/package.json
  test/integration/uninstrumented/uninstrumented.test.js
  test/lib/temp-override-uncaught.js
  test/lib/temp-remove-listeners.js
  test/unit/collector/facts.test.js
Labels: dev:tests

#2866 ci: Updated codecov-action to latest released version sha
  .github/workflows/ci-workflow.yml
Labels: dev:automation

#2869 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2874 chore: Updated versioned tests docs
  test/versioned/Readme.md
Labels: dev:tests

#2876 test: Updated a langchain test to be less rigid on asserting the tracking metric by `@langchain/core` version
  test/versioned/langchain/vectorstore.test.js
Labels: dev:tests

#2879 test: Restored the branch to test apollo-server-plugin to main
  test/versioned-external/external-repos.js
Labels: dev:tests

#2883 chore: Fixed dns integration tests
  test/integration/core/dns.test.js
Labels: dev:tests

#2886 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2893 test: Improved test coverage of normalizing claude 3 messages
  test/unit/llm-events/aws-bedrock/bedrock-command.test.js
Labels: dev:tests

#2888 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2902 docs: Updated compatibility report
  compatibility.md
Labels: documentation

#2911 chore: Added regex note to sql obfuscator
  lib/util/sql/obfuscate.js
Labels: documentation

#2915 ci: Optimized the lambda layers and k8s init containers post release workflow
  .github/workflows/release-lambda-init-containers.yml
Labels: dev:automation
